---
web_app_env: dev
web_project_name: php-app
web_project_root: "{{ playbook_dir | dirname }}"
web_nginx_container_name: "{{ web_project_name }}-nginx"
web_php_fpm_container_name: "{{ web_project_name }}-php-fpm"
web_nginx_conf_path: /etc/nginx/conf.d/default.conf
web_php_web_root: /var/www/html
web_logrotate_path: /etc/logrotate.d/nginx
web_container_user: www-data
web_container_log_group: adm
web_temp_render_dir: "/tmp/{{ web_project_name }}-ansible"
web_nginx_listen_port: 80
web_php_fpm_upstream: "{{ web_php_fpm_container_name }}:9000"
web_logrotate_temp_path: /tmp/logrotate-nginx
web_nginx_temp_conf_path: /tmp/nginx.conf
web_php_temp_index_path: /tmp/index.php
web_php_pool_temp_path: /tmp/php-fpm-www.conf
web_php_fpm_pool_path: /usr/local/etc/php-fpm.d/www.conf
web_php_pm: dynamic
web_php_pm_max_children: 10
web_php_pm_start_servers: 4
web_php_pm_min_spare_servers: 2
web_php_pm_max_spare_servers: 6
web_php_pm_max_requests: 500
web_php_pm_process_idle_timeout: 10s
web_php_pm_status_path: /status
